[phases.setup]
nixPkgs = ["python311", "curl"]

[phases.install]
cmds = ["curl -sS https://bootstrap.pypa.io/get-pip.py | python", "python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[start]
cmd = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"

